import "@/styles/globals.css";

import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import { TRPCReactProvider } from "@/trpc/react";
import { type NavItem, NavigationBar } from "../components/navigation-bar";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      className={cn(geist.variable, geist.variable, "font-sans", inter.variable)}
      lang="en"
      suppressHydrationWarning
    >
      <body>
        <TRPCReactProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            disableTransitionOnChange
            enableSystem
          >
            <NavigationBar
              enableBlock
              navItems={navItems}
              pageItems={pageItems}
              title="Template"
            />
            {children}
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}

const navItems: NavItem[] = [
  {
    name: "Home",
    href: "/",
  },
  {
    name: "Maintenance",
    href: "/maintenance",
  },
  {
    name: "Dashboard",
    href: "/dashboard",
  },
];

const pageItems: NavItem[] = [
  {
    name: "Home",
    href: "/",
  },
  {
    name: "Maintenance",
    href: "/maintenance",
  },
  {
    name: "Dashboard",
    href: "/dashboard",
  },
];
